// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXN-mgKsk1dKMo94kedVAFOObC-I-15Vc',
    appId: '1:366492429164:web:c7be66745162970b5ae149',
    messagingSenderId: '366492429164',
    projectId: 'lingobreeze-8856b',
    authDomain: 'lingobreeze-8856b.firebaseapp.com',
    storageBucket: 'lingobreeze-8856b.firebasestorage.app',
    measurementId: 'G-WGX9EX7CSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsdVzYjTIOpzdWWoMRF0P9smauno_Um88',
    appId: '1:366492429164:android:be230b7bb0bcc8fc5ae149',
    messagingSenderId: '366492429164',
    projectId: 'lingobreeze-8856b',
    storageBucket: 'lingobreeze-8856b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2vUOxYU6vrCKr5aDOU6i_zy510JBauw0',
    appId: '1:366492429164:ios:d5c5bdcbbfd5a4655ae149',
    messagingSenderId: '366492429164',
    projectId: 'lingobreeze-8856b',
    storageBucket: 'lingobreeze-8856b.firebasestorage.app',
    iosBundleId: 'com.example.lingobreeze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2vUOxYU6vrCKr5aDOU6i_zy510JBauw0',
    appId: '1:366492429164:ios:d5c5bdcbbfd5a4655ae149',
    messagingSenderId: '366492429164',
    projectId: 'lingobreeze-8856b',
    storageBucket: 'lingobreeze-8856b.firebasestorage.app',
    iosBundleId: 'com.example.lingobreeze',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXN-mgKsk1dKMo94kedVAFOObC-I-15Vc',
    appId: '1:366492429164:web:3431f81916aa5b435ae149',
    messagingSenderId: '366492429164',
    projectId: 'lingobreeze-8856b',
    authDomain: 'lingobreeze-8856b.firebaseapp.com',
    storageBucket: 'lingobreeze-8856b.firebasestorage.app',
    measurementId: 'G-HGHC4V20JF',
  );
}
